package engine.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.time.LocalDateTime;


 //Entity class representing a completed activity log. This log contains information
 //about the user who completed the activity, the activity itself, and the time at which
 //the activity was completed.
@Entity
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class CompletedLog {

     //This is the unique identifier for this log, generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Long logId;
    //The unique identifier for the user who completed the activity.
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Long userId;
    private Integer id;
    private LocalDateTime completedAt;

    // Constructor taking in the user who completed the activity, the activity itself, and the time
    //at which the activity was completed.
    public CompletedLog(Long userId, Integer id, LocalDateTime completedAt) {
        this.userId = userId;
        this.id = id;
        this.completedAt = completedAt;
    }
}
